"""add document content

Revision ID: 4d2df48762d6
Revises: f4854b7325eb
Create Date: 2025-12-14 01:00:40.877656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2df48762d6'
down_revision = 'f4854b7325eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_json', sa.Text(), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('confidentiality', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('confidentiality')
        batch_op.drop_column('content_json')

    # ### end Alembic commands ###
