"""add assigned_to_role

Revision ID: 951ac1202ca5
Revises: 4d2df48762d6
Create Date: 2025-12-14 23:00:15.314871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951ac1202ca5'
down_revision = '4d2df48762d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_role', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_document_assigned_to_role'), ['assigned_to_role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_assigned_to_role'))
        batch_op.drop_column('assigned_to_role')

    # ### end Alembic commands ###
